/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeriaproject.vistas;

import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import pizzeriaproject.jdbc.CategoriasJDBC;
import pizzeriaproject.jdbc.ProductosJDBC;
import pizzeriaproject.modelos.Categoria;
import pizzeriaproject.modelos.Producto;

/**
 *
 * @author krist
 */
public class VistaPoductos extends javax.swing.JPanel {

    ProductosJDBC conexionJDBC = new ProductosJDBC();
    DefaultTableModel tablaProductosModel = new DefaultTableModel();
    CategoriasJDBC conexionCategoriaJDBC = new CategoriasJDBC();
    List<Categoria> listaCategoria = new ArrayList<>();

    public VistaPoductos() {
        initComponents();
        this.configurarModelo();
        this.obtenerDatosCategoria();

    }

    private void configurarModelo() {
        String[] titulosTabla = {"id", "nombre", "Tipo Categoria"};
        tablaProductosModel.setColumnIdentifiers(titulosTabla);
        jTableProductos.setModel(tablaProductosModel);

    }
    private void agregarProductoNuevo(){
    String nombreProducto = jtextNombreProducto.getText();
    Integer idCategoria = Integer.parseInt(this.obtenerIdCategoriaComboBox());
    conexionJDBC.crearDatosProducto(idCategoria, nombreProducto);
    this.mostrarDatos();
    }

    private void mostrarDatos() {
        System.out.println("Buscando Categroias");
        try {
            List<Producto> listaProductos = this.conexionJDBC.obtenerDatosProducto();
            if (!listaProductos.isEmpty()) {
                Object[] datos = new Object[tablaProductosModel.getColumnCount()];

                this.limpiarTabla();

                for (Producto productos : listaProductos) {
                    datos[0] = productos.getId();
                    datos[1] = productos.getNombreProducto();
                    datos[2] = productos.getIdCategoria();

                    tablaProductosModel.addRow(datos);
                }

                jTableProductos.setModel(tablaProductosModel);
            } else {
                System.out.println("NO HAY DATOS");
            }

        } catch (SQLException ex) {
            Logger.getLogger(VistaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void limpiarTabla() {
        for (int i = tablaProductosModel.getRowCount() - 1; i >= 0; i--) {
            tablaProductosModel.removeRow(i);
        }
    }

    private void obtenerDatosCategoria() {
        System.out.println("Buscando Categroias");
        try {
            this.listaCategoria = this.conexionCategoriaJDBC.obtenerDatosCategoria();
            if (listaCategoria.isEmpty()) {
                System.out.println("NO HAY DATOS");
            } else {
                this.llenarComboBox();
            }

        } catch (SQLException ex) {
            Logger.getLogger(VistaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void llenarComboBox() {

        // Agrega las categorías al JComboBox
        for (Categoria categoria : listaCategoria) {
            jComboBoxCategoria.addItem("(" + categoria.getCodigo() + ") " + categoria.getNombre());
        }
    }

    private String obtenerIdCategoriaComboBox() {
        // Obtén el ID de la categoría seleccionada
        String idCategoriaSeleccionada
                = jComboBoxCategoria.getSelectedItem().toString();

        String[] partes = idCategoriaSeleccionada.split("\\(|\\)");
        String valor = partes[1];
        return valor;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarProductos = new javax.swing.JButton();
        jtextNombreProducto = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        btnAgregarNeuvoProducto = new javax.swing.JButton();

        btnBuscarProductos.setText("Buscar Productos");
        btnBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductosActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        btnAgregarNeuvoProducto.setText("Agregar Producto");
        btnAgregarNeuvoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNeuvoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarProductos)
                    .addComponent(btnAgregarNeuvoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtextNombreProducto)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBuscarProductos)
                .addGap(58, 58, 58)
                .addComponent(btnAgregarNeuvoProducto)
                .addGap(18, 18, 18)
                .addComponent(jtextNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNeuvoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNeuvoProductoActionPerformed
        this.agregarProductoNuevo();
    }//GEN-LAST:event_btnAgregarNeuvoProductoActionPerformed

    private void btnBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductosActionPerformed
        // TODO add your handling code here:
        this.mostrarDatos();
    }//GEN-LAST:event_btnBuscarProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNeuvoProducto;
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jtextNombreProducto;
    // End of variables declaration//GEN-END:variables
}
